site_name: json2vars-setter
site_description: GitHub Action to parse JSON files and set GitHub Actions outputs with version management capabilities
repo_name: 7rikazhexde/json2vars-setter
repo_url: https://github.com/7rikazhexde/json2vars-setter
edit_uri: edit/main/docs/
site_url: https://7rikazhexde.github.io/json2vars-setter/
copyright: "&copy; 2025 7rikazhexde"

theme:
  name: material
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode (system preference)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link
    - search.highlight
    - toc.follow
    - navigation.footer

extra_css:
  - stylesheets/mermaid-custom.css

extra_javascript:
  - https://unpkg.com/mermaid@10.8.0/dist/mermaid.min.js
  - javascripts/mermaid-custom.js

plugins:
  - search
  - git-revision-date-localized:
      type: date
      timezone: Asia/Tokyo        # タイムゾーンの設定
      locale: ja                  # 日本語での日付表示
      exclude:
        - index.md                # index.mdを除外
      enable_creation_date: true  # 作成日も表示したい場合

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Features:
      - Overview: features/index.md
      - JSON to Variables: features/json-to-variables.md
      - Dynamic Update: features/dynamic-update.md
      - Version Caching: features/version-caching.md
  - Usage Examples:
      - Basic Examples: examples/basic.md
      - CI/CD Integration: examples/ci-cd.md
      - Troubleshooting: examples/troubleshooting.md
  - Reference:
      - Command Options: reference/options.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/7rikazhexde
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tw_7rikazhexde
  consent:
    title: Cookie consent
    description: >-
      This site uses Google Analytics and cookies to collect visitor data.
      The collected data helps me understand site usage and improve the documentation.
      By clicking "Accept", you consent to the use of cookies for these purposes.
  analytics:
    provider: google
    property: G-CPBNH4WS82
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thank you for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thank you for your feedback!<br>
            Please feel free to reach out via Twitter for any suggestions
            or improvements.
