name: Deploy GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'zensical.toml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: Set variables from JSON
        id: json2vars
        uses: 7rikazhexde/json2vars-setter@v1.2.0
        with:
          json-file: .github/json2vars-setter/sample/cicd_matrix.json
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 33836132+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ fromJson(steps.json2vars.outputs.versions_python)[0] }}
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          enable-cache: true
      - run: echo "cache_id=$(date --utc '+%V')" >> "$GITHUB_ENV"
      - name: Create cache directory
        run: mkdir -p .cache
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        with:
          key: zensical-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            zensical-
      - name: Install dependencies
        run: uv sync --frozen
      - name: Build documentation
        run: uv run zensical build --clean
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
