name: Node.js Test

on:
  push:
    branches:
      - 'issue_no17'
    paths:
      - 'examples/nodejs/**'
      - '.github/workflows/nodejs_test.yml'

jobs:
  set_variables:
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.json2vars.outputs.os }}
      versions_nodejs: ${{ steps.json2vars.outputs.versions_nodejs }}
      ghpages_branch: ${{ steps.json2vars.outputs.ghpages_branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set variables from JSON
        id: json2vars
        uses: ./
        with:
          json-file: .github/workflows/nodejs_project_matrix.json

      - name: Debug output values
        run: |
          echo "os: ${{ steps.json2vars.outputs.os }}"
          echo "versions_nodejs: ${{ steps.json2vars.outputs.versions_nodejs }}"
          echo "ghpages_branch: ${{ steps.json2vars.outputs.ghpages_branch }}"

  run_tests:
    needs: set_variables
    strategy:
      matrix:
        os: ${{ fromJson(needs.set_variables.outputs.os) }}
        node-version: ${{ fromJson(needs.set_variables.outputs.versions_nodejs) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
          # Enable caching of npm dependencies
          cache: 'npm'
          cache-dependency-path: './examples/nodejs/package-lock.json'

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"

      - name: Display Node.js version
        run: |
          node --version
          npm --version

      - name: Install dependencies
        working-directory: ./examples/nodejs
        run: npm ci

      - name: Show matrix
        shell: bash
        run: |
          # For non-list case
          ghpages_branch="${{ needs.set_variables.outputs.ghpages_branch }}"

          # For list case, explicitly enclose the list in "" to make it a string. (Note that it is not ''.)
          os='${{ needs.set_variables.outputs.os }}'
          versions_nodejs='${{ needs.set_variables.outputs.versions_nodejs }}'

          echo "os: $os"
          echo "versions_nodejs: ${versions_nodejs}"
          echo "ghpages_branch: ${ghpages_branch}"

          # For loop case
          os_list=$(echo "${os}" | jq -r '.[]' | tr '\n' ' ' | sed 's/ $//')
          nodejs_versions_list=$(echo "${versions_nodejs}" | jq -r '.[]' | tr '\n' ' ' | sed 's/ $//')

          for current_os in ${os_list}; do
            for version in ${nodejs_versions_list}; do
              echo "Current OS: ${current_os}, Current Node.js Version: ${version}"
            done
          done

      - name: Run tests
        id: npm_test
        working-directory: ./examples/nodejs
        shell: bash
        run: |
          output="$(npm test)"
          echo "${output}"
